### ISSUE TITLE
Document roadmap to 1.0

### ISSUE THREAD

**Issue by captbaritone** [platinumazure/eslint-plugin-microtemplates#5]
It would be nice to decide what features/confirmations we are waiting on before we feel like we are ready for a stable 1.0 release.

Are there pieces of the codebase which feel incomplete or under tested? Are we waiting until we have implemented additional features?

**Comment by platinumazure** [comment]
I'll work on a milestone map this week, but here's a very rough list of the bare minimum I see being needed for a 1.0 release (and I'll update this as I think of more, until I finally put it into a formal milestone):
- [x] Trim code during extraction (to avoid `no-trailing-spaces` errors)
- [ ] Implement auto-fix (In progress upstream)
- [ ] User configuration of rules to be suppressed (blocked, depends on ESLint passing in settings to processors)
- [ ] User configuration of file extension types to be supported (blocked, depends on ESLint passing in settings to plugins)
- [ ] User configuration of template delimiters (blocked, depends on ESLint passing in settings to processors)
